version: '3.9'

services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: db
